### ISSUE TITLE
PreProsser会向./input/目录下写文件（Windows下会报错）

### ISSUE THREAD

**Issue by CZWin32768** [jiweixing/bit-minic-compiler#8]
老师您好
这学期学习编译原理课，发现了这样的错误：
看了反编译的结果，PreProcesser类里有一行向./input/目录下写文件，造成如下的错误：

![1](https://user-images.githubusercontent.com/12969670/28744360-cd6b4d80-7491-11e7-9329-a3287a87219d.PNG)

为了不在运行时报错，就必须在run目录下设置一个input文件夹，这样会容易让使用者与项目主目录下的input文件夹产生混淆，影响框架上手速度。

解决方案：重新生成pp.jar 把多余的那一行代码去掉

**Comment by marche147** [comment]
Closed as fixed in commit a580a2318132060049391053b341a321346daf1e.
